### ISSUE TITLE
[Bug]: clicking on the svg won't switch the theme

### ISSUE THREAD

**Issue by giacomocerquone** [surjithctly/astro-color-scheme#7]
Hey there.
Using your playground https://stackblitz.com/edit/github-jpfnv9-ep5z59?file=src%2Fpages%2Findex.astro you will notice that if you start clicking exclusively on the icon, and not on the button, the theme won't switch.

Check the video:

https://github.com/surjithctly/astro-color-scheme/assets/9303791/417f8267-6757-4d4f-b3a1-4164fc8ca962

That's because using `e.target` will give you the exact element the user has clicked on which might not be the button and, consequently, you'll lose the correct value of the `value` attribute you set.
You need to use `e.currentTarget`

**Comment by surjithctly** [comment]
Thanks for the bug & PR. #8 is merged
