### ISSUE TITLE
Change current page restart input state on switcher

### ISSUE THREAD

**Issue by isaico** [surjithctly/astro-color-scheme#9]
Hi, i have this issue when use two pages "/" and "/en"  for the same content but in English, when checkbox strategy it's used the check ☑ mark will always reload and change the state, causing a desync on the value of the box and the current theme.

` <ThemeSwitch strategy="checkbox" defaultTheme="system">
        <div class="flex py-2">
            <input type="checkbox" id="switch" name="switch" />
            <label for="switch"></label>
        </div>
    </ThemeSwitch>
`
I am using Astro, so can I use the transition:persist? Could you give some example? 

edit: when i change the page, the local storage value remains, but the theme actually doesn't sync, I can make some screens if you like

**Comment by surjithctly** [comment]
Can you make a reproductible repo / stackblitz link?

**Comment by isaico** [comment]
> Can you make a reproductible repo / stackblitz link?

https://proyect-ig-portfolio.vercel.app/

**Comment by surjithctly** [comment]
Hi,

Try adding `data-astro-reload` to the `<a>` link which toggles to the `/en` page.

**Comment by isaico** [comment]
It Works! Thanks for your support

**Comment by isaico** [comment]
Just for the record, the Viewtransition property won't work with that `<a>` attribute
